### ISSUE TITLE
Missing link to blog

### ISSUE THREAD

**Issue by jeremyallenjacobson** [addishp/QTM350_aws_project#1]
Can you upload the html or notebook that your used for your blogpost? Someone I know is working with Rekognition and is interested in your results. Thanks!

**Comment by addishp** [comment]
Hi Dr. Jacobson, 

That's great to hear! I'll let the team know! 

Here is the notebook link covering the findings: 
(1) https://github.com/addishp/QTM350_aws_project/blob/main/QTM_350_data_analysis.ipynb
Data collection notebooks: 
(1) https://github.com/addishp/QTM350_aws_project/blob/main/Data_Collection.ipynb 
(2) https://github.com/addishp/QTM350_aws_project/blob/main/Final%20Project%20Data%20Collection.ipynb

Have a great day,
Haniel
